version: "3.8"

services:
  synapse:
    image: matrixdotorg/synapse:latest
    # command: generate
    volumes:
      - "./data:/data"
    environment:
      SYNAPSE_SERVER_NAME: myserver.invalid
      SYNAPSE_REPORT_STATS: "no"
    ports:
      - "8008:8008"
  postgres:
    image: postgres:latest
    volumes:
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "8009:5432"
