version: "3.8"

services:
  synapse:
    image: matrixdotorg/synapse:latest
    # command: generate
    volumes:
      - "./data:/data"
    environment:
      SYNAPSE_SERVER_NAME: myserver.invalid
      SYNAPSE_REPORT_STATS: "no"
    ports:
      - "8008:8008"
      - "9009:9009"
  # redis:
  #   image: redis
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
  postgres:
    image: postgres:latest
    volumes:
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "8009:5432"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
